### PR TITLE
TCP update

### PR DESCRIPTION
**Pull request by sheharyaar**
Hi. Sorry for the late PR, had some examinations. I made changes for tcp. I am getting the error when starting client,
error: Nexthop has invalid gateway

I believe the Helium client is not starting.

I have removed the udp codes and debug messages from lightway-laser just to test tcp, so that I won't get confused.

### CODE REVIEW

**Comment by expressvpn-pete-m** [comment]
I'll try to test this out either today or tomorrow and get back to you with feedback. I really appreciate all the work you've put in so far!

In the meantime, can you share where you see the:

```
error: Nexthop has invalid gateway
```

log message? A full log file would be super useful :)

From memory, you can expect to see that error when you try to set a gateway that isn't on a directly attached network. For example if your only local network is `192.168.1.0/24`, and you tried to add a gateway to say `8.8.8.8` via `10.0.0.1`, it would fail with `Nexthop has invalid gateway`, because there's no direct path to `10.0.0.1`.

So this is most likely to happen when the new routes are added during the connection phase. I suspect that either the `tun` device isn't configured, or if it is, the gateway that is being used is on a different range somehow. 

I'll take a look through your code and hopefully in the meantime the above will give you some ideas of where the problem might be :)

**Comment by sheharyaar** [comment]
This error is displayed on running `scripts/run_iperf-client.sh` after running docker compose and starting server:

```console
root@3032c8495e33:/lw_reference# scripts/run_iperf_client.sh 
Resolved to target 172.18.0.2 server 172.18.0.3
Check that we have connectivity to the lightway server
PING 172.18.0.3 (172.18.0.3) 56(84) bytes of data.
64 bytes from 172.18.0.3: icmp_seq=1 ttl=64 time=0.124 ms

--- 172.18.0.3 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.124/0.124/0.124/0.000 ms
[6:47:54.002476s] Starting client...
[6:47:54.002699s] Connecting to:        172.18.0.3:19655
[6:47:54.002721s] Username:             test
[6:47:54.002733s] Client cert:          certs/shared.crt
[6:47:54.002744s] Streaming Mode:       true
[6:47:54.002755s] Tun device:           helium-test
Setting route to 172.18.0.2 via 10.125.0.2
Error: Nexthop has invalid gateway.
```

Thanks for the info.

**Comment by expressvpn-pete-m** [comment]
@sheharyaar Sorry for the delay in getting back to you! I hit the same issue as you when running the test harness. However, it's not very debug friendly in its current form (the test harness), so I'm looking to make some tweaks to try and help with that.

I think the problem is that the client is exiting before the route command is run which is what you also suspected.

I'll be actively looking at this over the next day or two :)

**Comment by sheharyaar** [comment]
Is the following change in my pr correct? 
File : src/tun/tun_util.c
Line : 101
> 
> \-  int s = socket(address_family, SOCK_DGRAM | SOCK_CLOEXEC, 0);
> \+  int s = socket(address_family, SOCK_STREAM | SOCK_CLOEXEC, 0);

If I terminate the server keeping the client running, then the client shows connection close, this shows that the client is able to connect to the server. I feel there is issue with tunnel setup.

**Comment by expressvpn-pete-m** [comment]
I've just looked into that section of the code, and I reckon you've probably found at least part of the issue. In this case `s` is used as a way to send `ioctl` commands to the `tun` driver. It's not actually a socket we use to send data. If you look at the end of the function, you'll see we call `close(s)` to close it before returning.

Try setting it back to `SOCK_DGRAM` and see what you get :)

**Comment by sheharyaar** [comment]
After changing it to `SOCK_DGRAM` it gives the following error:

```console
Resolved to target 172.18.0.3 server 172.18.0.2
Check that we have connectivity to the lightway server
PING 172.18.0.2 (172.18.0.2) 56(84) bytes of data.
64 bytes from 172.18.0.2: icmp_seq=1 ttl=64 time=0.020 ms

--- 172.18.0.2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.020/0.020/0.020/0.000 ms
[17:17:32.096997s] Starting client...
[17:17:32.097228s] Connecting to:        172.18.0.2:19655
[17:17:32.097249s] Username:             test
[17:17:32.097261s] Client cert:          certs/shared.crt
[17:17:32.097272s] Streaming Mode:       true
[17:17:32.097283s] Tun device:           helium-test
Setting route to 172.18.0.3 via 
Error: inet address is expected rather than "".
```

**Pull request closed without merging**
